import type { Metadata } from 'next'
import Providers from '../utils/providers'

import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/images/favicon.ico',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, user-scalable=no" />
      <body className={`font-pretendardMedium antialiased`}>
        <Providers>
          <div className="m-auto min-w-[300px] max-w-[600px]">{children}</div>
        </Providers>
      </body>
    </html>
  )
}
